### ISSUE TITLE
Akashlytics Deploy- Wallet shows 0 AKT balance

### ISSUE THREAD

**Issue by ctc27954** [Akashlytics/akashlytics-deploy#80] opened 2022-04-21 20:13 UTC
Hey there.  

I'm new....and 
I'm  trying to add a few akt to the -lytics Deploy to create a certificate. 
I am running the latest version v0.11.2 on Windows 10

I sent AKT from an exchange to my wallet address displayed in the dashboard
Dashboard stills shows a 0 balance but mainnet network   (135.181.181.122) also has 10056+ms latency + foreboding red dot .  

I imagine the dashboard is just having difficulty updating balance b/c latency.  https://akash.aneka.io/ shows the transaction and the destination wallet correctly.

Is there an alternative node IP I can use to at least get a balance to show in dashboard so I can create my certificate?

Thank you for any help

I can provide a redacted screenshot if ya'll do that sort of thing

**Comment by baktun14** [comment] 2022-04-22 17:24
Hey, sometimes the node available is slow... Is your situation resolved?

**Comment by ctc27954** [comment] 2022-04-23 12:52
Hi There
Thanks for the reply.  It is not.  The IP is not pingable from multiple
networks
[image: 0 AKT.PNG]

**Comment by baktun14** [comment] 2022-05-16 14:42
I will close this issue because it's not reproduceable.

**Closed by baktun14** 2022-05-16 14:42 UTC
